config/routes.rb
DojoTodo::Application.routes.draw do

  resources :notes

  resources :todos

  resources :pages

  match "/tutorial/:tutorial/:step" => "pages#tutorial", :as=>"tut"
  match "/tutorial/:tutorial" => "pages#toc", :as=>"toc"
  match "/welcome" => "home#welcome", :as=>"welcome"

end

app/models/note.rb
class Note < ActiveRecord::Base

  belongs_to :todo
end

app/models/page.rb
class Page < ActiveRecord::Base

  def next
    @next_page = Page.find_by_step(self.step+1)
  end

  def prev
    @prev_page = Page.find_by_step(self.step-1)
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  #This sets up up the default output format for data (object etc)
  #returned from the controller.
  respond_to :json, :html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def welcome

  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.xml
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to(@note, :notice => 'Note was successfully created.') }
        format.xml  { render :xml => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(@note, :notice => 'Note was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(notes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.xml
  def index
    @pages = Page.order([:tutorial,:step]).all

    respond_with @pages
  end

  # GET /pages/1
  # GET /pages/1.xml
  def show
    @page = Page.find(params[:id])
    respond_with @pages
  end

  # GET /pages/new
  # GET /pages/new.xml
  def new
    @page = Page.new

    respond_with @pages
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.xml
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to(@page, :notice => 'Page was successfully created.') }
        format.xml  { render :xml => @page, :status => :created, :location => @page }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.xml
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to(@page, :notice => 'Page was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.xml
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to(pages_url) }
      format.json  { head :ok }
    end
  end

  def tutorial
    @page = Page.where(:tutorial=>params[:tutorial]).where(:step=>params[:step])
    @page = @page[0]
    respond_with @page
  end

  def toc
    @pages = Page.select([:id,:title,:step,:tutorial]).where(:tutorial=>params[:tutorial])
    respond_with @pages
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  # GET /todos.xml
  def index
    @todos = Todo.all
    respond_with @todos
  end

  # GET /todos/1
  # GET /todos/1.xml
  def show
    @todo = Todo.find(params[:id])

    respond_with @todo
  end

  # GET /todos/new
  # GET /todos/new.xml
  def new
    @todo = Todo.new

    respond_with @todo
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.xml
  def create
    @todo = Todo.new(params[:todo])

    @todo.save
    respond_with @todo
  end

  # PUT /todos/1
  # PUT /todos/1.xml
  def update
    @todo = Todo.find(params[:id])
    @todo.update_attributes(params[:todo])

    respond_with @todo
  end

  # DELETE /todos/1
  # DELETE /todos/1.xml
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to(pages_url) }
      format.json  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/welcome.html.haml
%h1 Dojo Widget - 101

app/views/layouts/application.html.haml
%html
  %head
    %title Todo Dojo Widget Tutorial
    =stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/dojo/1.6/dijit/themes/tundra/tundra.css"
    =stylesheet_link_tag "base.less", :type=>"text/css", :rel=>"stylesheet/less"
    =stylesheet_link_tag "widget.less", :type=>"text/css", :rel=>"stylesheet/less"
    =javascript_include_tag "http://lesscss.googlecode.com/files/less-1.1.0.min.js"
    =javascript_include_tag "http://ajax.googleapis.com/ajax/libs/dojo/1.6/dojo/dojo.xd.js", :djConfig=>"isDebug: false, baseUrl: '/javascripts/', modulePaths: { 'my' : 'my', 'example': 'example' }"
    =csrf_meta_tag
  %body.tundra
    %header
      Dojo Widgets - Tutorial 1
    #page
      #content
        =yield
      #sidebar
        #example
        :javascript
          dojo.require("example.Todo");
          dojo.require("my.Todo");

          dojo.addOnLoad(function () {
            var widget = new example.Todo({

            },'example');

            var myWidget = new my.Todo({},'mywidget');
          })
        #mywidget

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :todo %><br />
    <%= f.text_field :todo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Todo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.title %></td>
    <td><%= note.content %></td>
    <td><%= note.todo %></td>
    <td><%= link_to 'Show', note %></td>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Content:</b>
  <%= @note.content %>
</p>

<p>
  <b>Todo:</b>
  <%= @note.todo %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :width=>'100%', :style=>"background-color:white; width: 100%", :id=>"editor" %>
  </div>
  <div class="field">
    <%= f.label :step %><br />
    <%= f.text_field :step %>
  </div>
  <div class="field">
    <%= f.label :tutorial %><br />
    <%= f.text_field :tutorial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  dojo.require("dijit.Editor");
  dojo.require("dijit._editor.plugins.FontChoice");
  dojo.addOnLoad(function () {
    var editorField = dojo.byId("editor");


    var editor = new dijit.Editor({
      extraPlugins: ['formatBlock']
    },"editor");
  });
</script>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Previous', @page.prev %> |
<%= link_to 'Show', @page %> |
<%= link_to 'Next', @page.next %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th colspan='2'>Title</th>
    <th>Tutorial</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td>Step <%= page.step %>:</td>
    <td><%= page.title %></td>
    <td><%= page.tutorial %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @page.step %>. <%= @page.title %></h1>

<%= raw @page.content %>

<p>
<%= link_to 'Previous', @page.prev %> |
<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Next', @page.next %> |
<%= link_to 'Table of Contents', pages_path %>
</p>

app/views/pages/toc.html.haml
-@pages.each do |p|
  .item=link_to p.step.to_s << ". " << p.title, tut_path(p.tutorial,p.step)

app/views/pages/tutorial.html.haml
#notice= notice

%h1= @page.step.to_s << ". " << @page.title
!= @page.content

=link_to 'Table of Contents', toc_path(@page.tutorial)
=link_to 'Next', tut_path(@page.tutorial,(@page.step+1))

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :done %><br />
    <%= f.date_select :done %>
  </div>
  <div class="field">
    <%= f.label :group %><br />
    <%= f.text_field :group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Done</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todos.each do |todo| %>
  <tr>
    <td><%= todo.name %></td>
    <td><%= todo.done %></td>
    <td><%= todo.group %></td>
    <td><%= link_to 'Show', todo %></td>
    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <td><%= link_to 'Destroy', todo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @todo.name %>
</p>

<p>
  <b>Done:</b>
  <%= @todo.done %>
</p>

<p>
  <b>Group:</b>
  <%= @todo.group %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>